name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pep517
        python -m pep517.build --binary --out-dir dist .
        # Install optional dependencies
        python -c "import toml; from pathlib import Path; \
                   data = toml.load(Path('pyproject.toml')); \
                   opt_deps = data.get('project', {}).get('optional-dependencies', {}); \
                   for deps in opt_deps.values(): \
                       for dep, ver in deps.items(): \
                           print(f'{dep}{ver}', end=' '); \
                  " | xargs pip install
        pip install dist/*.whl
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
