name: Ruff Check

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install Ruff
      run: pip install ruff
    - name: Run Ruff Linting
      run: ruff check .
